version: "3.7"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: challenge
    container_name: challenge-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www/
    networks:
      - challenge

  db:
    image: mysql:5.7
    container_name: challenge-db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - challenge

  nginx:
    image: nginx:1.17-alpine
    container_name: challenge-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./nginx:/etc/nginx/conf.d
    networks:
      - challenge

networks:
  challenge:
    driver: bridge

volumes:
  mysqldata:
    driver: local
